added mx test repo support for MX systems only

diff --git a/ddm-mx b/ddm-mx
--- a/ddm-mx
+++ b/ddm-mx
@@ -26,6 +26,8 @@ ERR_FILE="/dev/null"
 LOG="/var/log/ddm.log"
 BP_REPO="stretch-backports"
 BP_REPO_ADDRESS="deb http://ftp.debian.org/debian"
+MX_TEST_REPO_ADDRESS="deb http://la.mxrepo.com/mx/testrepo/ stretch test"
+
 
 TEXTDOMAINDIR=/usr/share/locale 
 export TEXTDOMAIN="ddm-mx"
@@ -47,10 +49,11 @@ trap clean_up EXIT
 do_flock 
 
 
-# --force-yes is deprecated in stretch
-FORCE='--force-yes'
+#get release info
 source /etc/lsb-release
-
+echo
+echo "Distribution:  " $DISTRIB_ID
+echo
 
 # -------------------------------------------------------------------------
 
@@ -98,21 +101,12 @@ done
 # Is there anything to do?
 if [ "$INSTALL" == "" ]; then
   TEST=false
-#  if [ "$PURGE" == "" ]; then
-    # Started without anything to install or purge
-    #launch_gui $@
-#  fi
 fi
 
 # From here onward: be root
 if [ $UID -ne 0 ]; then
   echo $RUN_AS_ROOT | tee -a $LOG
   exit 1
-fi
-
-# If not running in terminal, use GUI frontend
-if [ ! -t 1 ]; then
-  export DEBIAN_FRONTEND=gnome
 fi
 
 # Log file for traceback
@@ -323,7 +317,11 @@ echo ""
   echo ""
 
   MAIN_CAND=$CANDIDATE
-  debian_backports_dialog
+  if [ "$DISTRIB_ID" = "MX" ]; then
+    mx_test_repo_dialog
+  else
+    debian_backports_dialog
+  fi
   check_cand
 
   if [ -f /etc/apt/sources.list.d/debian-backports-temp.list ]; then
@@ -340,6 +338,28 @@ echo ""
        echo $"Installed is: " $INSTALLED | tee -a $LOG
        echo ""
        which_driver
+       echo ""
+      fi 
+  else
+      echo $"Candidate is: " $CANDIDATE | tee -a $LOG
+      echo $"Installed is: " $INSTALLED | tee -a $LOG
+      echo ""
+  fi  
+  
+  if [ -f /etc/apt/sources.list.d/mx-test-repo-temp.list ]; then
+      if [ "$MAIN_CAND" = "$CANDIDATE" ]; then 
+       echo $"Candidate is: " $CANDIDATE | tee -a $LOG
+       echo $"MX Test repo candidate is:  "  $CANDIDATE |tee -a $LOG
+       echo $"Installed is: " $INSTALLED | tee -a $LOG
+       echo ""
+       BP=""
+       SWITCH=""
+      else
+       echo $"Main repo candidate is:  " $MAIN_CAND |tee -a $LOG
+       echo $"MX Test repo candidate is:  "  $CANDIDATE |tee -a $LOG
+       echo $"Installed is: " $INSTALLED | tee -a $LOG
+       echo ""
+       which_driver_mx
        echo ""
       fi 
   else
@@ -523,6 +543,11 @@ if [ -f /etc/apt/sources.list.d/debian-backports-temp.list ]; then
   apt-get update
   echo ""
 fi
+if [ -f /etc/apt/sources.list.d/mx-test-repo-temp.list ]; then
+    rm -f /etc/apt/sources.list.d/mx-test-repo-temp.list
+    apt-get update
+    echo ""
+fi
 echo -n $"Press <Enter> to exit" | tee -a $LOG 
 read x
 }
@@ -552,6 +577,24 @@ enable_debian_backports()
   echo ""
 }
 
+enable_mx_test_repo()
+{
+#enabling mx_test_repo
+  echo $"Enabling MX Test repo"
+  echo $"Running apt-get update..."
+  echo "$MX_TEST_REPO_ADDRESS">>/etc/apt/sources.list.d/mx-test-repo-temp.list
+  apt-get update |tee -a $LOG
+  if [ $? = 100 ]; then
+    echo $"There was a problem with the apt-get update.  See $LOG for details"
+    my_exit
+  fi
+  echo ""
+  echo $"Installing latest nvidia-detect package"|tee -a $LOG
+  echo ""
+  apt-get install nvidia-detect |tee -a $LOG  
+  echo ""
+}
+
 debian_backports_dialog()
 {
 echo $"Would you like to check debian-backports for a later version?" | tee -a $LOG
@@ -575,6 +618,31 @@ echo $"Would you like to check debian-backports for a later version?" | tee -a $
            *) echo $"invalid option."  $"exiting"... | tee -a $LOG && exit 0;;
         esac
 }
+
+mx_test_repo_dialog()
+{
+echo $"Would you like to check MX Test Repo for a later version?" | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo $"Yes or No?" | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo 1: $"Yes" | tee -a $LOG
+        echo 2: $"No" | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo "Enter Number of selection" | tee -a $LOG
+        read -n 1 -e x
+
+        case $x in
+           1)   echo $"Ok"...| tee -a $LOG 
+                SWITCH=""
+                BP="" 
+                enable_mx_test_repo	;;
+           2)   echo $"Ok"... | tee -a $LOG
+                SWITCH=""
+                BP=""           ;;
+           *) echo $"invalid option."  $"exiting"... | tee -a $LOG && exit 0;;
+        esac
+}
+
 
 which_driver()
 {
@@ -604,6 +672,40 @@ echo $"Which driver do you wish to install" | tee -a $LOG
            *) echo $"invalid option."  $"exiting"... | tee -a $LOG && exit 0;;
         esac
 }
+
+which_driver_mx()
+{
+echo $"Which driver do you wish to install" | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo $"Main repos or MX Test" | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo 1: $"Main" $MAIN_CAND| tee -a $LOG
+        echo "" | tee -a $LOG
+        echo 2: "MX Test" $CANDIDATE | tee -a $LOG
+        echo "" | tee -a $LOG
+	echo 3: $"Exit" | tee -a $LOG
+        echo "" | tee -a $LOG
+        echo $"Enter Number of selection" | tee -a $LOG
+        read -n 1 -e x
+
+        case $x in
+           1) echo $"Ok"...| tee -a $LOG 
+                SWITCH=""
+                BP=""
+                rm /etc/apt/sources.list.d/mx-test-repo-temp.list
+                apt-get update
+                    ;;
+           2)   echo $"Ok"... | tee -a $LOG
+                SWITCH=""
+                BP=""
+                #NVIDIA_XCONFIG=""
+                     ;;
+           3) echo $"exiting" |tee -a $LOG && exit 0;;
+
+           *) echo $"invalid option."  $"exiting"... | tee -a $LOG && exit 0;;
+        esac
+}
+
 
 check_cand()
 {
