added "reinstall" routine

diff --git a/ddm-mx b/ddm-mx
--- a/ddm-mx
+++ b/ddm-mx
@@ -441,26 +441,29 @@ function install_fglrx {
   echo "Candidate is: " $CANDIDATE
   echo "Installed is: " $INSTALLED
 
-  if [ "$INSTALLED" = "$CANDIDATE" ]; then
-    echo $"ati/amd driver already installed"
-    echo ""
-    echo $"Reinstall or quit?"
-    echo ""
-    echo 1: $"Reinstall"
-    echo 2: $"quit"
-    echo ""
-    echo "Enter Number of selection"
-    read -n 1 -e x
+  if [ "$CANDIDATE" != "" ]; then
+      if [ "$INSTALLED" = "$CANDIDATE" ]; then
+        echo $"ati/amd driver already installed"
+        echo ""
+        echo $"Reinstall or quit?"
+        echo ""
+        echo 1: $"Reinstall"
+        echo 2: $"quit"
+        echo ""
+        echo "Enter Number of selection"
+        read -n 1 -e x
 
-    case $x in
-        1) echo $"reinstalling"... ;;
-        2) echo $"exiting"... && exit 0 ;;
-        *) echo $"invalid option."  $"exiting"... ;;
-    esac
+        case $x in
+            1) echo $"reinstalling"... ;;
+            2) echo $"exiting"... && exit 0 ;;
+            *) echo $"invalid option."  $"exiting"... ;;
+        esac
+      fi
   fi
 
   if [ "$CANDIDATE" == "" ]; then
-    exit 4
+    echo $"fglrx driver not available, check your repo sources"
+    exit 3
   fi
 
   echo "Need driver: $DRIVER ($CANDIDATE)" | tee -a $LOG
@@ -670,22 +673,24 @@ function install_nvidia {
   echo "Candidate is: " $CANDIDATE
   echo "Installed is: " $INSTALLED
 
-  if [ "$INSTALLED" = "$CANDIDATE" ]; then
-    echo $"nvidia driver already installed"
-    echo ""
-    echo $"Reinstall or quit?"
-    echo ""
-    echo 1: $"Reinstall"
-    echo 2: $"quit"
-    echo ""
-    echo "Enter Number of selection"
-    read -n 1 -e x
+  if [ "$CANDIDATE" != "" ]; then
+      if [ "$INSTALLED" = "$CANDIDATE" ]; then
+        echo $"nvidia driver already installed"
+        echo ""
+        echo $"Reinstall or quit?"
+        echo ""
+        echo 1: $"Reinstall"
+        echo 2: $"quit"
+        echo ""
+        echo "Enter Number of selection"
+        read -n 1 -e x
 
-     case $x in
-        1) echo $"reinstalling"... ;;
-        2) echo $"exiting"... && exit 0 ;;
-        *) echo $"invalid option."  $"exiting"... ;;
-    esac
+        case $x in
+            1) echo $"reinstalling"... ;;
+            2) echo $"exiting"... && exit 0 ;;
+            *) echo $"invalid option."  $"exiting"... ;;
+        esac
+      fi
   fi
 
   if [ "$DRIVER" == "" ] || [ "$CANDIDATE" == "" ]; then
